skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_first_contract = "Bf7actXnieXdkfSFYyaBG2DQ7WPtVdUQUNnpmspM47Yf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
